name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [8, 10, 12, 14]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: npm install

    - name: (coverage) Install
      if: matrix.nodejs >= 14
      run: npm install -g nyc

    - name: Test
      run: npm test
      if: matrix.nodejs < 14

    - name: Test w/ Coverage
      run: nyc --include=src npm test
      if: matrix.nodejs >= 14

    - name: Report Coverage
      if: matrix.nodejs >= 14
      run: |
        nyc report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
